import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";

const eslintConfig = defineConfig([
  ...nextVitals,

  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "coverage/**",
    "next-env.d.ts",
    // Generated by the shadcn CLI. Owned but not hand-authored; restyled
    // through the token layer rather than edited ad hoc.
    "src/components/ui/**",
  ]),

  {
    files: ["src/**/*.{ts,tsx}"],
    rules: {
      /**
       * The Zero Raw Hex rule (DESIGN.md §6).
       *
       * The previous build accumulated 565 inline hex literals across 18
       * distinct values with no token layer. Every colour must come from a
       * CSS custom property so the two themes stay in sync and the contrast
       * audit in scripts/verify-contrast.mjs can actually see them.
       *
       * Colours live in src/app/globals.css. Nowhere else.
       */
      "no-restricted-syntax": [
        "error",
        {
          selector:
            "Literal[value=/^#(?:[0-9a-fA-F]{3,4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$/]",
          message:
            "Raw hex colour. Use a design token (bg-primary, text-muted-foreground, var(--warning)). Colours are defined only in src/app/globals.css.",
        },
        {
          selector:
            "TemplateElement[value.raw=/#(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{3})\\b/]",
          message:
            "Raw hex colour in a template literal. Use a design token instead.",
        },
        {
          selector: "CallExpression[callee.name='useQuery']",
          message:
            "Call the resource hook (useCases, useCase, …) rather than useQuery directly. Query keys and invalidation live in one place; see docs/DESIGN_SCREENS.md §12.",
        },
        {
          selector: "CallExpression[callee.name='useMutation']",
          message:
            "Call the resource hook rather than useMutation directly, so the invalidation set stays colocated. See docs/DESIGN_SCREENS.md §12.",
        },
      ],
    },
  },

  {
    // The hooks layer is where useQuery/useMutation are allowed to live.
    files: ["src/lib/query/**", "src/features/**/api/**"],
    rules: { "no-restricted-syntax": "off" },
  },
]);

export default eslintConfig;
