-- V2__add_case_audit_tables.sql
-- Schema for Hibernate Envers auditing in tenant schemas

CREATE TABLE IF NOT EXISTS revinfo (
    rev INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revtstmp BIGINT,
    user_id VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS recovery_case_aud (
    id UUID NOT NULL,
    rev INT NOT NULL,
    revtype SMALLINT,
    tenant_id UUID,
    assignee_id UUID,
    contract_id UUID,
    initial_residual_value_cents BIGINT,
    currency_code VARCHAR(3),
    current_phase VARCHAR(50),
    phase_started_at TIMESTAMP WITH TIME ZONE,
    last_action_at TIMESTAMP WITH TIME ZONE,
    status VARCHAR(50),
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_rcase_aud_revinfo FOREIGN KEY (rev) REFERENCES revinfo(rev)
);
